const crystals = {
  crystal_8: () => import('./Crystal.glb?url'),
  crystal_2: () => import('./Crystal-3saqXqoOti.glb?url'),
  crystal_24: () => import('./Crystal-5dXobG8vsp.glb?url'),
  crystal_10: () => import('./Crystal-7Do2pm4F8O.glb?url'),
  crystal_25: () => import('./Crystal-7iHQpCXTb7.glb?url'),
  crystal_18: () => import('./Crystal-8Tt6H5IwAC.glb?url'),
  crystal_14: () => import('./Crystal-9MyZG1W4lZ.glb?url'),
  crystal_12: () => import('./Crystal-BpirJ95GzN.glb?url'),
  crystal_21: () => import('./Crystal-dxCmHfpqc5.glb?url'),
  crystal_6: () => import('./Crystal-dY99VgAUtS.glb?url'),
  crystal_7: () => import('./Crystal-Ftu5CcnxFZ.glb?url'),
  crystal_28: () => import('./Crystal-fvPiJt42Q1.glb?url'),
  crystal_19: () => import('./Crystal-H4cOcCir1M.glb?url'),
  crystal_5: () => import('./Crystal-hT8NFrVTMq.glb?url'),
  crystal_9: () => import('./Crystal-JABQ8uEVz0.glb?url'),
  crystal_3: () => import('./Crystal-kfdC7vKiD6.glb?url'),
  crystal_17: () => import('./Crystal-KvI5ZmiQHY.glb?url'),
  crystal_22: () => import('./Crystal-MlhTJAFuJY.glb?url'),
  crystal_20: () => import('./Crystal-N0yUOaSuL9.glb?url'),
  crystal_1: () => import('./Crystal-nyCeR6poJX.glb?url'),
  crystal_13: () => import('./Crystal-oNWj2mo2vS.glb?url'),
  crystal_11: () => import('./Crystal-r0eKL45nP5.glb?url'),
  crystal_27: () => import('./Crystal-SbLlgMXrQ1.glb?url'),
  crystal_23: () => import('./Crystal-tEF4oKBc3A.glb?url'),
  crystal_26: () => import('./Crystal-Wj8Qjq38T8.glb?url'),
  crystal_15: () => import('./Crystal-wkuYn6x3UL.glb?url'),
  crystal_4: () => import('./Crystal-WzWPKHFMkL.glb?url'),
  crystal_16: () => import('./Crystal-ySa8IekR6i.glb?url'),
};

export default crystals;
